añadir_rss=Add to RSS
añadir_rss_titulo=Add %cancion% to your RSS
añadir_rss_todas=Add all these songs to your RSS
quitar_rss=Remove from RSS
quitar_rss_titulo=Remove %cancion% from your RSS
mostrar_rss=Show your RSS URL
ocultar_rss=Hide your RSS URL
mostrar_informacion_descargas=Show download information
ocultar_informacion_descargas=Hide download information
añadir_paquete=Add to package
añadir_paquete_titulo=Add to the song download package
quitar_paquete=Remove from package
quitar_paquete_titulo=Remove from the song download package
descargar_paquete=Download package
canciones_paquete=(%num% song added) | (%num% songs added)
max_paquete=You cannot add any more songs to the package. Download the current package before adding more songs.
num_paquete={1}You must have at least 1 song in the package | {2}You must have at least 2 songs in the package
vaciar_paquete_pregunta=Are you sure you want to empty the song package?
no_previsualizacion=No preview available
;PLAYLIST
añadir_lista=Add to playlist
añadir_lista_titulo=Add to playlist
quitar_lista=Remove from playlist
quitar_lista_titulo=Remove from playlist
borrar_lista=Are you sure you want to delete this playlist?
borrar_cancion=Are you sure you want to delete this song?
abrir=Open
abrir_lista=Playlist closed. Click to open it and add songs
cerrar=Close
cerrar_lista=Playlist open. You can now add songs. Click to close it
;UPLOAD
subir_archivo=This file cannot be uploaded. Please check the list above.
subir_archivo_tamaño=File size is too large
