añadir_rss=Aldoni al RSS
añadir_rss_titulo=Aldoni %cancion% al via RSS
añadir_rss_todas=Aldoni ĉiujn ĉi tiujn kantojn al via RSS
quitar_rss=Forigi el RSS
quitar_rss_titulo=Forigi %cancion% el via RSS
mostrar_rss=Montri la URL-on de via RSS
ocultar_rss=Kaŝi la URL-on de via RSS
mostrar_informacion_descargas=Montri elŝutajn informojn
ocultar_informacion_descargas=Kaŝi elŝutajn informojn
añadir_paquete=Aldoni al pakaĵo
añadir_paquete_titulo=Aldoni al la elŝutota kantopakaĵo
quitar_paquete=Forigi el pakaĵo
quitar_paquete_titulo=Forigi el la elŝutota kantopakaĵo
descargar_paquete=Elŝuti pakaĵon
canciones_paquete=(%num% kanto aldonita) | (%num% kantoj aldonitaj)
max_paquete=Vi ne povas aldoni pliajn kantojn al la pakaĵo. Elŝutu la nunan pakaĵon antaŭ ol aldoni pliajn.
num_paquete={1}Vi devas havi almenaŭ 1 kanton en la pakaĵo | {2}Vi devas havi almenaŭ 2 kantojn en la pakaĵo
vaciar_paquete_pregunta=Ĉu vi vere volas malplenigi la kantopakaĵon?
no_previsualizacion=Neniu antaŭrigardo disponeblas
;PLAYLIST
añadir_lista=Aldoni al ludlisto
añadir_lista_titulo=Aldoni al ludlisto
quitar_lista=Forigi el ludlisto
quitar_lista_titulo=Forigi el ludlisto
borrar_lista=Ĉu vi vere volas forigi ĉi tiun ludliston?
borrar_cancion=Ĉu vi vere volas forigi ĉi tiun kanton?
abrir=Malfermi
abrir_lista=Ludlisto fermita. Alklaku por malfermi ĝin kaj aldoni kantojn
cerrar=Fermi
cerrar_lista=Ludlisto malfermita. Vi povas aldoni kantojn. Alklaku por fermi ĝin
;UPLOAD
subir_archivo=Ĉi tiu dosiero ne povas esti alŝutita. Bonvolu kontroli la supran liston.
subir_archivo_tamaño=La dosiero estas tro granda
