añadir_rss=Aggiungi all'RSS
añadir_rss_titulo=Aggiungi %cancion% al tuo RSS
añadir_rss_todas=Aggiungi tutti questi brani al tuo RSS
quitar_rss=Rimuovi dall'RSS
quitar_rss_titulo=Rimuovi %cancion% dal tuo RSS
mostrar_rss=Mostra l'URL del tuo RSS
ocultar_rss=Nascondi l'URL del tuo RSS
mostrar_informacion_descargas=Mostra informazioni sui download
ocultar_informacion_descargas=Nascondi informazioni sui download
añadir_paquete=Aggiungi al pacchetto
añadir_paquete_titulo=Aggiungi al pacchetto dei brani da scaricare
quitar_paquete=Rimuovi dal pacchetto
quitar_paquete_titulo=Rimuovi dal pacchetto dei brani da scaricare
descargar_paquete=Scarica pacchetto
canciones_paquete=(%num% brano aggiunto) | (%num% brani aggiunti)
max_paquete=Non puoi aggiungere altri brani al pacchetto. Scarica quelli già presenti e poi potrai aggiungerne altri.
num_paquete={1}Devi avere almeno 1 brano nel pacchetto | {2}Devi avere almeno 2 brani nel pacchetto
vaciar_paquete_pregunta=Vuoi davvero svuotare il pacchetto dei brani?
no_previsualizacion=Nessuna anteprima disponibile
;PLAYLIST
añadir_lista=Aggiungi alla playlist
añadir_lista_titulo=Aggiungi alla playlist
quitar_lista=Rimuovi dalla playlist
quitar_lista_titulo=Rimuovi dalla playlist
borrar_lista=Vuoi davvero eliminare questa playlist?
borrar_cancion=Vuoi davvero eliminare questo brano?
abrir=Apri
abrir_lista=Playlist chiusa. Fai clic per aprirla e aggiungere brani
cerrar=Chiudi
cerrar_lista=Playlist aperta. Puoi aggiungere brani. Fai clic per chiuderla
;UPLOAD
subir_archivo=Impossibile caricare questo file. Controlla l'elenco qui sopra.
subir_archivo_tamaño=Il file è troppo grande
