;HEADER
cancion=Song | Songs
lista=Playlist | Playlists
peticion=Song request | Song requests
subir_cancion=Upload new songs
base_canciones=Song database
silabeador=Song syllabifier
reparador=Song repair tool
insertar=Submit new songs
concursos=Competitions
puntuacion=Score | Scores
batallas=Battles
programas=Programs
ayuda=Help
foro=Forum
ver_perfil=View your user profile
cambiar_avatar=Change avatar
desconectarse=Disconnect
cerrar_sesion=Log out
mensajes=%mensajes% new message|%mensajes% new messages
mostrar_informacion_descargas_titulo=Information about your torrent downloads
mostrar_rss_titulo=Show the URL of your RSS feed for downloading songs
info_rss=What is RSS and how do I use it to download songs?
tiempo_conexion=Connection time
estado_servidor=Server status
estado_servidor_tiempo=Offline|Online %tiempo%
canciones_disponibles=Available songs
descargado_total=Total downloaded
subido_total=Total uploaded
descargado=Total downloaded by you
subido=Total uploaded by you
ratio=Your upload/download ratio
puesto_bajada=Download ranking
puesto_subida=Upload ranking
conectate=Sign in
iniciar_sesion=Log in
registrate=sign up!
registro=or, if you don't have an account, %registrate%
contraseña_olvidada=Forgotten password?
contraseña_olvidada_titulo=Recover your forgotten password
reenviar_activacion=Resend activation
reenviar_activacion_titulo=Resend activation email
pagina_idioma=View page in %idioma%
pagina_idioma_actual=Page displayed in %idioma%
;PAGINATOR
mostrando_no=There are no %item% to display
mostrando_pagina=Showing %total% %item%
mostrando_paginas=Showing %item% %desde% to %hasta% of %total%
mostrando_ultimas=Showing the latest %numero% %ultimas%
mostrando_ultimas_cancion=latest %item% added
mostrando_ultimas_lista=latest %item% updated
mostrando_ultimas_peticion=%item% from the last week
mostrando_ultimas_puntuacion=%item% from the last day
mostrando_ultimas_concursos=latest competitions added
ordenar_por=Sort by
ordenadas_por=sorted by
defecto=Default
mostrar=Show %item%
todas=All
ir_a_pagina=Go to page
ir_a_pagina_numero=Go to page %numero%
ir_a_primera=Go to the first results page
ir_a_anterior=Go to the previous results page
ir_a_siguiente=Go to the next results page
ir_a_ultima=Go to the last results page
ver_pagina=View results page %pagina%
subir_arriba=Back to top
;HOME
slider_worldparty=Try our %worldparty% version
slider_canciones=Download songs from your favourite artists
slider_puntuaciones=Upload your scores and compare them with other players
slider_peticiones=Can't find your favourite song? Request one every month!
algo_mas_karaoke=More than just karaoke on your computer
algo_mas_karaoke_p1=All you need is a microphone, a computer, our %worldparty%, and the thousands of songs we make available to you.
algo_mas_karaoke_p2=To help you start singing as quickly as possible, we provide a series of video tutorials explaining how to install and configure the game.
algo_mas_karaoke_p3=Once you've followed them, simply download the %canciones% you want, add them to %ultrastar%, and show off your singing talent.
algo_mas_karaoke_p4=If you still have any questions, you can browse the rest of the %ayuda% section or search for, or request, further information in the %foro%.
ultimas_noticias=Latest news
publicado_por=Published by %autor% on %fecha%
x_lecturas=%lecturas% views
leer_mas=Read more
ultimas_puntuaciones=Latest scores
mejores_puntuaciones_dia=Best scores today
mejores_puntuaciones_semana=Best scores this week
mejores_puntuaciones_mes=Best scores this month
puntuaciones_anteriores=Previous scores
puntuaciones_siguientes=Next scores
ultimas_canciones=Latest songs added
canciones_descargas=Most downloaded songs
canciones_descargas_mensuales=Most downloaded songs in the last month
canciones_descargas_semanales=Most downloaded songs in the last week
canciones_descargas_diarias=Most downloaded songs in the last 24 hours
canciones_anteriores=Previous songs
canciones_siguientes=Next songs
;WORLDPARTY DOWNLOAD
worldparty_titulo2=Have fun singing your favourite songs!
worldparty_p1=Discover the world of %worldparty%. An enhanced version we have created from the original UltraStar Deluxe.
worldparty_p2=Without doubt, it is the most feature-rich and up-to-date version available. It includes everything you would expect (singing scores, Party Mode, easy song management, and much more), together with a wide range of improvements and new features.
worldparty_p3=Among the most important features are: singing duets with another person, performing shortened versions of songs, Jukebox mode to play your songs continuously, sending your scores to the website, using your computer's webcam while singing, supporting up to six players singing simultaneously on the same screen, and much more.
worldparty_p4=You can find all the information in the section dedicated to %worldparty%.
worldparty_descargar=Download %worldparty%
worldparty_version_para=%version% version for %plataforma%
;SONGS
descargar_canciones=Download songs
busqueda_titulo=containing
ver_todas_titulo=View all songs %titulo% %dato%
artista=Artist
idioma=Language
idioma_titulo=in
año=Year
año_titulo=from
sin_año=Unknown
subida_por=Uploaded by
subida_por_titulo=uploaded by
revisada_por=Send a private message to the reviewer
valoracion=Rating
valoracion_titulo=View ratings for %cancion%
descargas=Downloads
tamaño=Size
fecha=Date
semillas=Seeders
sanguijuelas=Leechers
otros=Others
baja_calidad=Low-quality song
alta_calidad=High-quality song
validada_titulo=Someone has achieved at least %facil% points on Easy | %normal% points on Medium | %dificil% points on Hard
multijugador=Multiplayer
solo_titulo=No single-player version available
fondo_titulo=Uses a background image instead of a video
doradas_titulo=No golden notes
creador=Creator
artista_titulo=by
cancion_titulo=similar to
semana_titulo=uploaded during the week of
edicion_titulo=from the edition
lista_titulo=from the playlist
info_cancion=View complete information about %cancion%
previsualizacion=Preview %cancion%
copiar_video=Click to select the video URL
descargar=Download
descargar_titulo=Download the torrent for %cancion%
descargada_titulo=Download the torrent for %cancion% again
descargar_txt=Download TXT
descargar_txt_titulo=Download only the text file for %cancion%
descargar_todas=Download all displayed songs
descargar_todas_titulo=Download the torrents for all displayed songs as a ZIP archive
descargar_lista=Download playlist
descargar_lista_titulo=Download the playlist (UPL file) to group these songs in the game
descargar_paquete_titulo=Download the song package (ZIP archive) containing the torrents for all the songs you have added
ver_paquete=View song package
ver_paquete_titulo=View the contents of the song package to be downloaded
vaciar_paquete=Clear song package
vaciar_paquete_titulo=Clear the song package waiting to be downloaded
eliminar_lista=Delete playlist
eliminar_lista_titulo=Delete playlist
canciones_lista=one song added | %canciones% songs added
agradecer=Thank
agradecer_titulo=Thank the creator who uploaded this song
agradecimientos=Thanks
cerrar_informacion=Click or press ESC to close this information window
enlace_permanente=Permanent link
enviar_por_correo=Send by email
compartir_en=Share on %red%
estadisticas=Statistics
descargas_diarias=Daily downloads
descargas_semanales=Weekly downloads
descargas_mensuales=Monthly downloads
descargas_totales=Total downloads
cancion_no_disponible=Song currently unavailable
no_resultados=No results
disponibilidad=Availability
descargadas_alguna_vez=Downloaded at least once
descargadas_txt=Downloaded as TXT only
descargadas_torrent_rss=Downloaded via torrent or RSS
actualmente_rss=Currently in RSS
quitadas_rss=Removed from RSS
no_descargadas=Not downloaded
ultima_descarga=Since my last download
paquete=Added to the download package
mis_agradecimientos=With my thanks
rss_titulo=Songs by %usuario% on %web%
rss_titulo_subir=Songs uploaded by %usuario% to %web%
rss_titulo_insertar=Songs reviewed by %usuario% on %web%
;RATING
cambiar_estado=Change status
abrir_categoria=Expand/collapse category
guardar_valoracion=Save rating
sincronizacion=Synchronisation
sincronizacion_mala=Acceptable synchronisation
sincronizacion_aproximada=Very accurate synchronisation
sincronizacion_perfecta=Perfect synchronisation
duracion_mala=Acceptable note duration
duracion_aproximada=Very accurate note duration
duracion_perfecta=Perfect note duration
bpm=Correct BPM
notas=Notes
tonos_minimo=Acceptable pitch accuracy
tonos_aceptables=Very accurate pitch
tonos_revisados=Pitch reviewed
notas_doradas=Contains golden notes
notas_doradas_correctas=Golden notes correctly placed
ortografia=Spelling
errores_ortograficos=No spelling mistakes
tildes=Accents, quotation marks and other symbols correctly used
signos_puntuacion=No unnecessary punctuation marks
capitalizacion=Lines begin following a consistent capitalisation pattern
archivos=Files
tamaño_caratula=Acceptable cover image size
audio_calidad=Acceptable audio quality
fondo_video=Contains a background image or video
video_sincronizado=Video synchronised
video_sin_sonido=Video without audio
tamaño_video=Video size appropriate for its quality
lineas=Lines correctly split
medley=Short version of the song
inicio_fin=No unnecessary silence at the beginning or end
;PLAYLIST
mis_listas=View my playlists
mis_listas_texto=To add songs to one of your playlists, simply open it first, then browse to the Songs section and follow the instructions shown above. It's that easy!
crear_lista=Create a new playlist
crear_lista_texto=Enter a name and a description for the songs that the playlist will contain. These details cannot be changed later, so make them as descriptive as possible.
importar_lista=Import playlist
importar_lista_texto=If you have playlists created in UltraStar, you can import them here and share them with other users.
importar_lista_texto2=Only playlists containing two or more songs will be imported, and only songs whose title and artist match songs already in the database.
nombre=Name
usuario=User
fecha_actualizacion=Last updated
listas_propias=Created by me
buscar=Search
buscar_titulo=Search for all the songs included in this playlist
eliminar=Delete
creada_fecha=Created by %usuario% on %fecha%
modificada_fecha=and last updated on %fecha%
titulos_completos=Click here if some song titles are not fully visible
;REQUESTED
peticiones_texto=These are the songs that %ultrastar% users have requested.
peticiones_texto2=If the song you wanted to request has already been requested by someone else, you can vote for it instead. This helps creators see which songs are the most wanted. However, this does not mean that they will necessarily be created, or even created sooner.
fecha_insercion=Submission date
fecha_asignacion=Assignment date
pedida_por=Requested by
asignada_el_dia=Assigned on %dia%
asignada_a=Assigned to
no_hay=None
adjuntado_por=Attached by %usuario% on %fecha%
adjuntos=Attachments
adjuntos_titulo=View attachments
adjuntos_titulo_creadores=Available for download by creators only
tipo_midi=MIDI
tipo_video=Video
tipo_caratula=Cover image
tipo_audio=Audio
tipo_txt=Text file
nadie=Nobody
administrar=Manage
peticiones_propias=Requested by me
votaciones_propias=Voted by me
creadas_reparadas=Currently being created
realizadas=Completed
asignadas=Assigned to me
existentes=Rejected (already exists)
repetidas=Rejected (duplicate request)
datos_erroneos=Rejected (incorrect information)
no_asignada=Unassigned
asignada=In progress
reparada=Being repaired
realizada=Completed
repetida=Duplicate
erronea=Incorrect
votos=Vote | Votes
votos_totales=Total votes
votos_anuales=Yearly votes
votos_trimestrales=Quarterly votes
votos_mensuales=Monthly votes
votos_semanales=Weekly votes
votos_semana=You have %votos% vote remaining this week | You have %votos% votes remaining this week
votar=Vote
votar_titulo=Vote for this song
estado=Status
comentario=Comment
adjuntar_archivo=Attach file
editar_cancion=Edit song
hacer_cancion=I'll create this song
reparar_cancion=I'll repair this song
reiniciar_estado=Reset status
desasignar_cancion=Unassign this song from me
marcar_realizada=Mark song as completed
marcar_repetida=Mark song as a duplicate
marcar_erronea=Mark song as incorrect
pedir_cancion=Request a song
pedir_cancion_titulo=Request your monthly song
como_pedir_cancion=How to request songs and use this section
como_pedir_cancion_titulo=How to request your monthly song, vote for existing requests and attach files to help creators
pedir_cancion_texto=Here you can request one song each month from your favourite artists. If you're lucky, someone may create it for you, although in most cases it may never be created or it could take a very long time—even years!
pedir_cancion_texto2=Please do not make demands in the comments. Consider yourself fortunate if one day you are finally able to sing your requested song.
pedir_cancion_texto3=Before completing the form, check whether the song you want to request is already listed in %canciones% or among the existing %peticiones%.
pedir_cancion_texto4=These are all the details you can provide.
adjuntar_archivo_titulo=Attach a file to %artista% - %cancion%
adjuntar_archivo_texto=If you have any files that could help with creating this song, attach them here.
adjuntar_archivo_texto2=You must provide a link to the file. If you cannot host it elsewhere, upload it to %web% and use that link instead.
adjuntar_archivo_texto3=Please try to provide high-quality videos. If the video is already available on YouTube or a similar platform, there is no need to upload it again.
adjuntar_archivo_texto4=All fields are optional. If used, they must contain a complete URL, including http:// or https://.
;UPLOAD
rss_subir=This RSS feed contains all the songs you have uploaded to the website. Add it to your client so that you can continue sharing them.
tutorial_subir=Song upload tutorial
subir_archivos=You must now upload the following files before you can generate the torrent.
boton_añadir_archivos=Add files
boton_empezar_subida=Start uploading this file | Start uploading all files
boton_cancelar_subida=Cancel upload of this file | Cancel upload of all files
boton_eliminar=Remove this file | Remove selected files
generar_torrent_titulo=Before generating the torrent, you must upload all the files shown in the list above.
cancion_añadida=%cancion% has been successfully added to the review queue. Once it has been reviewed and approved, it will appear in the song database.
cancion_validada=The song %cancion% has been successfully validated.
cancion_no_validada=Song %cancion% has not been validated.
cancion_doradas=Contains %doradas% points in golden notes.
cancion_doradas_porcentaje=Contains %doradas%% golden notes.
cancion_jugador=for player %jugador%
cancion_hash=This song has the same hash as another song already present in the database.
;INSERT
autorevisor=If you want to be able to validate your own songs, you must upload %canciones% more songs with a rating higher than %valoracion%.
limite_actualizacion=You have updated %actualizadas% songs created by other authors out of a maximum of %limite%. This limit is calculated using a 1:%ratio% ratio based on your uploaded songs: the more songs you create, the more updates you will be allowed to make.
insertar_texto=Whenever you assign a song to yourself, it will automatically be added to this RSS feed, which contains every song you are currently reviewing or have reviewed in the past.
insertar_texto_creador=These are your songs awaiting validation by a Super Creator.
no_añadida_tracker=Song not yet added to the tracker.
enviar_mensaje=Send a private message to %usuario%
revisor=Reviewer
comentario_revisor=Comment for the reviewer
mostrar_comentario_revisor=Show/Hide comment for the reviewer
resubida_sin_cambios=Re-uploaded without changes
cancion_pedida=Requested song
cancion_actualizar=Song to be updated
revisar_cancion=Review song
no_revisar_cancion=Do not review song
no_editar_cancion=Do not edit song
valorar_cancion=Rate song
no_valorar_cancion=Do not rate song
marcar_categoria=Select/Deselect the entire category
insertar_cancion=Submit song
eliminar_cancion=Delete song
canciones_nuevas_semana=%num% new songs this week
;HELP
realizado_por=Created by %autor%
;SCORES
bajar_puntuaciones=Download the high scores file
bajar_puntuaciones_titulo=Only required to update %worldparty% high scores if you do not have an Internet connection.
subir_puntuaciones=Upload your high scores file
subir_puntuaciones_titulo=Here you can upload any scores you have saved locally but have not yet submitted using %worldparty%.
puntos=Points
nivel=Difficulty
nivel_titulo=on
nivel_facil=Easy
nivel_normal=Medium
nivel_dificil=Hard
fecha_titulo=on
puntos_normales=Regular points
puntos_lineas=Line bonus
puntos_doradas=Golden notes
;CONTEST
crear_duelo=Create duel
crear_torneo=Create tournament
crear_liga=Create league
mis_concursos=My competitions
clasificaciones=Rankings
ver_concurso=View competition
unirse_concurso=Join competition
concursos=Competitions
creada_por=Created by
tipo=Type
rondas_cada=Rounds every
inicio=Start
nivel=Difficulty
jugadores=Players
;403
acceso_no_permitido=Access denied
acceso_admin=Your account does not have the required permissions to access this section of the website.
acceso_login_texto=You must be logged in to access this section of the website.
;LOGIN
login_texto=You can use this form to sign in. If you do not yet have an account, %registrate%
login_registrate=sign up!
