;HEADER
cancion=Kanto | Kantoj
lista=Ludlisto | Ludlistoj
peticion=Petita kanto | Petitaj kantoj
subir_cancion=Alŝuti novajn kantojn
base_canciones=Kantodatumbazo
silabeador=Silabigilo
reparador=Kantoriparilo
insertar=Sendi novajn kantojn
concursos=Konkursoj
puntuacion=Poentaro | Poentaroj
batallas=Bataloj
programas=Programoj
ayuda=Helpo
foro=Forumo
ver_perfil=Montri vian profilon
cambiar_avatar=Ŝanĝi avataron
desconectarse=Malkonekti
cerrar_sesion=Elsaluti
mensajes=%mensajes% nova mesaĝo|%mensajes% novaj mesaĝoj
mostrar_informacion_descargas_titulo=Informoj pri viaj torrent-elŝutoj
mostrar_rss_titulo=Montri la URL-on de via RSS-fluo por elŝuti kantojn
info_rss=Kio estas RSS kaj kiel oni uzas ĝin por elŝuti kantojn?
tiempo_conexion=Konektotempo
estado_servidor=Servila stato
estado_servidor_tiempo=Senkonekta|Konektita %tiempo%
canciones_disponibles=Disponeblaj kantoj
descargado_total=Entute elŝutita
subido_total=Entute alŝutita
descargado=Entute elŝutita de vi
subido=Entute alŝutita de vi
ratio=Via alŝuta/elŝuta proporcio
puesto_bajada=Rango laŭ elŝutoj
puesto_subida=Rango laŭ alŝutoj
conectate=Ensalutu
iniciar_sesion=Ensaluti
registrate=registriĝu!
registro=aŭ, se vi ankoraŭ ne havas konton, %registrate%
contraseña_olvidada=Ĉu vi forgesis la pasvorton?
contraseña_olvidada_titulo=Reakiri forgesitan pasvorton
reenviar_activacion=Resendi aktivigon
reenviar_activacion_titulo=Resendi la aktivigan retmesaĝon
pagina_idioma=Montri la paĝon en %idioma%
pagina_idioma_actual=Paĝo montrata en %idioma%
;PAGINATOR
mostrando_no=Neniu %item% por montri
mostrando_pagina=Montrante %total% %item%
mostrando_paginas=Montrante %item% de %desde% ĝis %hasta% el %total%
mostrando_ultimas=Montrante la lastajn %numero% %ultimas%
mostrando_ultimas_cancion=lastaj aldonitaj %item%
mostrando_ultimas_lista=lastaj ĝisdatigitaj %item%
mostrando_ultimas_peticion=%item% de la pasinta semajno
mostrando_ultimas_puntuacion=%item% de la pasinta tago
mostrando_ultimas_concursos=lastaj aldonitaj konkursoj
ordenar_por=Ordigi laŭ
ordenadas_por=ordigitaj laŭ
defecto=Defaŭlte
mostrar=Montri %item%
todas=Ĉiuj
ir_a_pagina=Iri al paĝo
ir_a_pagina_numero=Iri al paĝo %numero%
ir_a_primera=Iri al la unua rezultpaĝo
ir_a_anterior=Iri al la antaŭa rezultpaĝo
ir_a_siguiente=Iri al la sekva rezultpaĝo
ir_a_ultima=Iri al la lasta rezultpaĝo
ver_pagina=Montri rezultpaĝon %pagina%
subir_arriba=Reiri al la supro
;HOME
slider_worldparty=Provu nian version de %worldparty%
slider_canciones=Elŝutu kantojn de viaj plej ŝatataj artistoj
slider_puntuaciones=Alŝutu viajn poentarojn kaj komparu ilin kun tiuj de aliaj ludantoj
slider_peticiones=Ĉu via plej ŝatata kanto mankas? Vi povas peti unu ĉiumonate!
algo_mas_karaoke=Pli ol simpla karaokeo en via komputilo
algo_mas_karaoke_p1=Vi bezonas nur mikrofonon, komputilon, nian %worldparty% kaj la milojn da kantoj, kiujn ni disponigas al vi.
algo_mas_karaoke_p2=Por ke vi povu komenci kanti kiel eble plej rapide, ni disponigas serion da videaj lerniloj, kiuj klarigas kiel instali kaj agordi la ludon.
algo_mas_karaoke_p3=Post tio vi nur bezonos elŝuti la %canciones% kiujn vi volas, aldoni ilin al %ultrastar% kaj montri vian kantotalenton.
algo_mas_karaoke_p4=Se vi ankoraŭ havas demandojn, vi povas konsulti la ceteron de la sekcio %ayuda% aŭ serĉi aŭ peti pliajn informojn en la %foro%.
ultimas_noticias=Plej novaj novaĵoj
publicado_por=Publikigita de %autor% je %fecha%
x_lecturas=%lecturas% legadoj
leer_mas=Legi plu
ultimas_puntuaciones=Plej novaj poentaroj
mejores_puntuaciones_dia=Plej bonaj poentaroj de hodiaŭ
mejores_puntuaciones_semana=Plej bonaj poentaroj de ĉi tiu semajno
mejores_puntuaciones_mes=Plej bonaj poentaroj de ĉi tiu monato
puntuaciones_anteriores=Antaŭaj poentaroj
puntuaciones_siguientes=Sekvaj poentaroj
ultimas_canciones=Plej laste aldonitaj kantoj
canciones_descargas=Plej elŝutitaj kantoj
canciones_descargas_mensuales=Plej elŝutitaj kantoj de la lasta monato
canciones_descargas_semanales=Plej elŝutitaj kantoj de la lasta semajno
canciones_descargas_diarias=Plej elŝutitaj kantoj de la lastaj 24 horoj
canciones_anteriores=Antaŭaj kantoj
canciones_siguientes=Sekvaj kantoj
;WORLDPARTY DOWNLOAD
worldparty_titulo2=Amuziĝu kantante viajn plej ŝatatajn kantojn!
worldparty_p1=Malkovru la mondon de %worldparty%. Plibonigita versio, kiun ni kreis surbaze de la malnova UltraStar Deluxe.
worldparty_p2=Sendube temas pri la plej kompleta kaj ĝisdata versio disponebla. Ĝi enhavas ĉion, kion oni povas atendi (kantopoentadon, Festan Reĝimon, facilan kantoadministradon, kaj multe pli), kune kun granda nombro da plibonigoj kaj novaj funkcioj.
worldparty_p3=Inter la plej gravaj funkcioj troviĝas: kanti duetojn kun alia persono, prezenti mallongigitajn versiojn de kantoj, uzi la Jukebox-reĝimon por seninterrompe ludi viajn kantojn, sendi viajn poentarojn al la retejo, uzi la retkameraon de via komputilo dum kantado, subteni ĝis ses samtempajn kantantojn sur la sama ekrano, kaj multe pli.
worldparty_p4=Ĉiujn informojn vi trovos en la sekcio dediĉita al %worldparty%.
worldparty_descargar=Elŝuti %worldparty%
worldparty_version_para=versio %version% por %plataforma%
;SONGS
descargar_canciones=Elŝuti kantojn
busqueda_titulo=enhavantaj
ver_todas_titulo=Montri ĉiujn kantojn %titulo% %dato%
artista=Artisto
idioma=Lingvo
idioma_titulo=en
año=Jaro
año_titulo=de la jaro
sin_año=Nekonata
subida_por=Alŝutita de
subida_por_titulo=alŝutitaj de
revisada_por=Sendi privatan mesaĝon al la revizianto
valoracion=Takso
valoracion_titulo=Montri la taksojn de %cancion%
descargas=Elŝutoj
tamaño=Grandeco
fecha=Dato
semillas=Semantoj
sanguijuelas=Suĉantoj
otros=Aliaj
baja_calidad=Malaltkvalita kanto
alta_calidad=Altkvalita kanto
validada_titulo=Iu atingis almenaŭ %facil% poentojn en Facila reĝimo | %normal% poentojn en Normala reĝimo | %dificil% poentojn en Malfacila reĝimo
multijugador=Plurludanta
solo_titulo=Unu-ludanta versio ne disponeblas
fondo_titulo=Uzas fonbildon anstataŭ videon
doradas_titulo=Ne enhavas orajn notojn
creador=Kreinto
artista_titulo=de
cancion_titulo=similaj al
semana_titulo=alŝutitaj dum la semajno de
edicion_titulo=de la eldono
lista_titulo=de la ludlisto
info_cancion=Montri ĉiujn informojn pri %cancion%
previsualizacion=Montri antaŭrigardon de %cancion%
copiar_video=Alklaku por elekti la URL-on de la video
descargar=Elŝuti
descargar_titulo=Elŝuti la torrenton de %cancion%
descargada_titulo=Elŝuti denove la torrenton de %cancion%
descargar_txt=Elŝuti TXT
descargar_txt_titulo=Elŝuti nur la tekstdosieron de %cancion%
descargar_todas=Elŝuti ĉiujn montratajn kantojn
descargar_todas_titulo=Elŝuti la torrentojn de ĉiuj montrataj kantoj en ZIP-arkivo
descargar_lista=Elŝuti ludliston
descargar_lista_titulo=Elŝuti la ludliston (UPL-dosieron) por grupigi ĉi tiujn kantojn en la ludo
descargar_paquete_titulo=Elŝuti la kantopakaĵon (ZIP-arkivon) enhavantan la torrentojn de ĉiuj aldonitaj kantoj
ver_paquete=Montri pakaĵon
ver_paquete_titulo=Montri la enhavon de la elŝutota kantopakaĵo
vaciar_paquete=Malplenigi pakaĵon
vaciar_paquete_titulo=Malplenigi la kantopakaĵon atendantan elŝuton
eliminar_lista=Forigi ludliston
eliminar_lista_titulo=Forigi ludliston
canciones_lista=unu kanto aldonita | %canciones% kantoj aldonitaj
agradecer=Danki
agradecer_titulo=Danki la kreinton, kiu alŝutis ĉi tiun kanton
agradecimientos=Dankoj
cerrar_informacion=Alklaku aŭ premu ESC por fermi ĉi tiun informfenestron
enlace_permanente=Konstanta ligilo
enviar_por_correo=Sendi retpoŝte
compartir_en=Kunhavigi per %red%
estadisticas=Statistikoj
descargas_diarias=Ĉiutagaj elŝutoj
descargas_semanales=Ĉiusemajnaj elŝutoj
descargas_mensuales=Ĉiumonataj elŝutoj
descargas_totales=Tutaj elŝutoj
cancion_no_disponible=Kanto nuntempe ne disponeblas
no_resultados=Neniuj rezultoj
disponibilidad=Disponebleco
descargadas_alguna_vez=Elŝutitaj almenaŭ unufoje
descargadas_txt=Elŝutitaj nur kiel TXT
descargadas_torrent_rss=Elŝutitaj per torrento aŭ RSS
actualmente_rss=Nuntempe en RSS
quitadas_rss=Forigitaj el RSS
no_descargadas=Neniam elŝutitaj
ultima_descarga=Ekde mia lasta elŝuto
paquete=Aldonitaj al la elŝuta pakaĵo
mis_agradecimientos=Kun miaj dankoj
rss_titulo=Kantoj de %usuario% ĉe %web%
rss_titulo_subir=Kantoj alŝutitaj de %usuario% al %web%
rss_titulo_insertar=Kantoj reviziitaj de %usuario% ĉe %web%
;RATING
cambiar_estado=Ŝanĝi staton
abrir_categoria=Malfermi/Fermi kategorion
guardar_valoracion=Konservi taksadon
sincronizacion=Sinkronigo
sincronizacion_mala=Akceptebla sinkronigo
sincronizacion_aproximada=Tre preciza sinkronigo
sincronizacion_perfecta=Perfekta sinkronigo
duracion_mala=Akceptebla noto-daŭro
duracion_aproximada=Tre preciza noto-daŭro
duracion_perfecta=Perfekta noto-daŭro
bpm=Ĝusta BPM
notas=Notoj
tonos_minimo=Akceptebla tonalto
tonos_aceptables=Tre preciza tonalto
tonos_revisados=Tonalto reviziita
notas_doradas=Enhavas orajn notojn
notas_doradas_correctas=Oraj notoj ĝuste lokitaj
ortografia=Ortografio
errores_ortograficos=Neniuj ortografiaj eraroj
tildes=Akcentoj, citiloj kaj aliaj simboloj ĝuste uzataj
signos_puntuacion=Neniuj superfluaj interpunkciaj signoj
capitalizacion=La linioj komenciĝas laŭ konsekvenca uzo de majuskloj kaj minuskloj
archivos=Dosieroj
tamaño_caratula=Taŭga grandeco de la kovrilbildo
audio_calidad=Taŭga sonkvalito
fondo_video=Enhavas fonbildon aŭ fonvideon
video_sincronizado=Video sinkronigita
video_sin_sonido=Video sen sono
tamaño_video=Videa grandeco taŭga al ĝia kvalito
lineas=Linioj ĝuste dividitaj
medley=Mallongigita versio de la kanto
inicio_fin=Neniu superflua silento ĉe la komenco aŭ la fino
;PLAYLIST
mis_listas=Montri miajn ludlistojn
mis_listas_texto=Por aldoni kantojn al unu el viaj ludlistoj, unue malfermu ĝin, poste iru al la sekcio Kantoj kaj sekvu la supre montritajn instrukciojn. Tio estas vere simpla!
crear_lista=Krei novan ludliston
crear_lista_texto=Enigu nomon kaj priskribon por la kantoj, kiujn la ludlisto enhavos. Tiuj informoj poste ne povos esti ŝanĝitaj, do provu fari ilin kiel eble plej priskribaj.
importar_lista=Importi ludliston
importar_lista_texto=Se vi havas ludlistojn kreitajn en UltraStar, vi povas importi ilin ĉi tie kaj kunhavigi ilin kun aliaj uzantoj.
importar_lista_texto2=Nur ludlistoj enhavantaj almenaŭ du kantojn estos importitaj, kaj nur kantoj kies titolo kaj artisto kongruas kun tiuj jam en la datumbazo.
nombre=Nomo
usuario=Uzanto
fecha_actualizacion=Lasta ĝisdatigo
listas_propias=Kreitaj de mi
buscar=Serĉi
buscar_titulo=Serĉi ĉiujn kantojn en ĉi tiu ludlisto
eliminar=Forigi
creada_fecha=Kreita de %usuario% je %fecha%
modificada_fecha=laste ĝisdatigita je %fecha%
titulos_completos=Alklaku ĉi tie se iuj kantotitoloj ne estas montrataj plene
;REQUESTED
peticiones_texto=Jen la kantoj petitaj de la uzantoj de %ultrastar%.
peticiones_texto2=Se la kanto, kiun vi volas peti, jam estis petita de alia uzanto, vi povas simple voĉdoni por ĝi. Tiel la kreintoj ekscios, kiuj kantoj estas la plej dezirataj. Tamen tio ne garantias, ke ili estos kreitaj aŭ ke tio okazos pli rapide.
fecha_insercion=Dato de la peto
fecha_asignacion=Dato de la atribuo
pedida_por=Petita de
asignada_el_dia=Atribuita je %dia%
asignada_a=Atribuita al
no_hay=Neniu
adjuntado_por=Aldonita de %usuario% je %fecha%
adjuntos=Aldonaĵoj
adjuntos_titulo=Montri aldonaĵojn
adjuntos_titulo_creadores=Elŝuteblaj nur por kreintoj
tipo_midi=MIDI
tipo_video=Video
tipo_caratula=Kovrilbildo
tipo_audio=Aŭdio
tipo_txt=Tekstdosiero
nadie=Neniu
administrar=Administri
peticiones_propias=Petitaj de mi
votaciones_propias=Voĉdonitaj de mi
creadas_reparadas=Nuntempe prilaborataj
realizadas=Finitaj
asignadas=Atribuitaj al mi
existentes=Rifuzitaj (jam ekzistas)
repetidas=Rifuzitaj (duobla peto)
datos_erroneos=Rifuzitaj (malĝustaj informoj)
no_asignada=Neatribuita
asignada=Prilaborata
reparada=Riparata
realizada=Finita
repetida=Duobla
erronea=Erara
votos=Voĉdono | Voĉdonoj
votos_totales=Totalaj voĉdonoj
votos_anuales=Jaraj voĉdonoj
votos_trimestrales=Kvaronjaraj voĉdonoj
votos_mensuales=Monataj voĉdonoj
votos_semanales=Semajnaj voĉdonoj
votos_semana=Restas al vi %votos% voĉdono ĉi-semajne | Restas al vi %votos% voĉdonoj ĉi-semajne
votar=Voĉdoni
votar_titulo=Voĉdoni por ĉi tiu kanto
estado=Stato
comentario=Komento
adjuntar_archivo=Aldoni dosieron
editar_cancion=Redakti kanton
hacer_cancion=Mi kreos ĉi tiun kanton
reparar_cancion=Mi riparos ĉi tiun kanton
reiniciar_estado=Restarigi staton
desasignar_cancion=Forigi mian atribuon al ĉi tiu kanto
marcar_realizada=Marki la kanton kiel finitan
marcar_repetida=Marki la kanton kiel duoblan
marcar_erronea=Marki la kanton kiel eraran
pedir_cancion=Peti kanton
pedir_cancion_titulo=Peti vian monatan kanton
como_pedir_cancion=Kiel peti kanton kaj uzi ĉi tiun sekcion
como_pedir_cancion_titulo=Lernu kiel peti vian monatan kanton, voĉdoni por ekzistantaj petoj kaj aldoni dosierojn utilajn al la kreintoj
pedir_cancion_texto=Ĉi tie vi povas peti unu kanton monate de via plej ŝatata artisto. Se vi bonŝancos, iu eble kreos ĝin por vi, kvankam plejofte ĝi eble neniam estos kreita aŭ tio povus postuli tre longan tempon, eĉ jarojn.
pedir_cancion_texto2=Bonvolu ne fari postulojn en la komentoj. Konsideru vin bonŝanca se iam vi finfine povos kanti la kanton, kiun vi petis.
pedir_cancion_texto3=Antaŭ ol plenigi la formularon, kontrolu ĉu la kanto, kiun vi volas peti, jam troviĝas inter la %canciones% aŭ inter la ekzistantaj %peticiones%.
pedir_cancion_texto4=Jen ĉiuj informoj, kiujn vi povas provizi.
adjuntar_archivo_titulo=Aldoni dosieron al %artista% - %cancion%
adjuntar_archivo_texto=Se vi havas dosierojn utilajn por krei ĉi tiun kanton, aldonu ilin ĉi tie.
adjuntar_archivo_texto2=Vi devas provizi ligilon al la dosiero. Se vi ne povas gastigi ĝin aliloke, alŝutu ĝin al %web% kaj uzu tiun ligilon.
adjuntar_archivo_texto3=Bonvolu provizi bonkvalitajn filmetojn. Se la video jam disponeblas en YouTube aŭ simila platformo, ne necesas alŝuti ĝin denove.
adjuntar_archivo_texto4=Ĉiuj kampoj estas nedevigaj. Se ili estas plenigitaj, ili devas enhavi kompletan URL-on, inkluzive de http:// aŭ https://.
;UPLOAD
rss_subir=Tiu ĉi RSS-fluo enhavas ĉiujn kantojn, kiujn vi alŝutis al la retejo. Aldonu ĝin al via kliento por daŭre kundividi ilin.
tutorial_subir=Lernilo pri alŝutado de kantoj
subir_archivos=Antaŭ ol generi la torrenton, vi devas alŝuti la jenajn dosierojn.
boton_añadir_archivos=Aldoni dosierojn
boton_empezar_subida=Komenci alŝuti ĉi tiun dosieron | Komenci alŝuti ĉiujn dosierojn
boton_cancelar_subida=Nuligi la alŝuton de ĉi tiu dosiero | Nuligi la alŝuton de ĉiuj dosieroj
boton_eliminar=Forigi ĉi tiun dosieron | Forigi la elektitajn dosierojn
generar_torrent_titulo=Antaŭ ol generi la torrenton, vi devas esti alŝutinta ĉiujn dosierojn en la supra listo.
cancion_añadida=%cancion% estis sukcese aldonita al la revizia atendovico. Post kiam ĝi estos reviziita kaj aprobita, ĝi aperos en la kantodatumbazo.
cancion_validada=La kanto %cancion% estis sukcese validigita.
cancion_no_validada=La kanto %cancion% ne estis validigita.
cancion_doradas=Enhavas %doradas% poentojn el oraj notoj.
cancion_doradas_porcentaje=Enhavas %doradas%% da oraj notoj.
cancion_jugador=de ludanto %jugador%
cancion_hash=Tiu ĉi kanto havas la saman haketaĵon kiel alia kanto jam ĉeestanta en la datumbazo.
;INSERT
autorevisor=Por povi validigi viajn proprajn kantojn, vi devas alŝuti ankoraŭ %canciones% kantojn kun takso pli alta ol %valoracion%.
limite_actualizacion=Vi ĝisdatigis %actualizadas% kantojn kreitajn de aliaj aŭtoroj el maksimume %limite%. Tiu limo estas kalkulata laŭ proporcio de 1:%ratio% rilate al la kantoj, kiujn vi alŝutis: ju pli da kantoj vi kreas, des pli da ĝisdatigoj vi povos fari.
insertar_texto=Ĉiufoje kiam vi atribuas kanton al vi mem, ĝi estos aŭtomate aldonita al ĉi tiu RSS-fluo, kiu enhavas ĉiujn kantojn, kiujn vi nun revizias aŭ jam reviziis.
insertar_texto_creador=Jen viaj kantoj atendantaj validigon fare de Supera Kreinto.
no_añadida_tracker=Kanto ankoraŭ ne aldonita al la spurilo.
enviar_mensaje=Sendi privatan mesaĝon al %usuario%
revisor=Revizianto
comentario_revisor=Komento por la revizianto
mostrar_comentario_revisor=Montri/Kaŝi la komenton por la revizianto
resubida_sin_cambios=Realŝutita sen ŝanĝoj
cancion_pedida=Petita kanto
cancion_actualizar=Ĝisdatigota kanto
revisar_cancion=Revizii kanton
no_revisar_cancion=Ne revizii la kanton
no_editar_cancion=Ne redakti la kanton
valorar_cancion=Taksi kanton
no_valorar_cancion=Ne taksi la kanton
marcar_categoria=Elekti/Malelekti la tutan kategorion
insertar_cancion=Sendi kanton
eliminar_cancion=Forigi kanton
canciones_nuevas_semana=%num% novaj kantoj ĉi-semajne
;HELP
realizado_por=Kreita de %autor%
;SCORES
bajar_puntuaciones=Elŝuti la poentaran dosieron
bajar_puntuaciones_titulo=Necesas nur por ĝisdatigi la poentarojn de %worldparty% kiam ne disponeblas Interreta konekto.
subir_puntuaciones=Alŝuti la poentaran dosieron
subir_puntuaciones_titulo=Ĉi tie vi povas alŝuti ĉiujn poentarojn konservitajn loke, kiuj ankoraŭ ne estis senditaj per %worldparty%.
puntos=Poentoj
nivel=Malfacileco
nivel_titulo=en reĝimo
nivel_facil=Facila
nivel_normal=Normala
nivel_dificil=Malfacila
fecha_titulo=je
puntos_normales=Ordinaraj poentoj
puntos_lineas=Linia gratifiko
puntos_doradas=Poentoj pro oraj notoj
;CONTEST
crear_duelo=Krei duelon
crear_torneo=Krei turniron
crear_liga=Krei ligon
mis_concursos=Miaj konkursoj
clasificaciones=Klasifikoj
ver_concurso=Montri konkurson
unirse_concurso=Aliĝi al konkurso
concursos=Konkursoj
creada_por=Kreita de
tipo=Tipo
rondas_cada=Raŭndoj ĉiujn
inicio=Komenco
nivel=Malfacileco
jugadores=Ludantoj
;403
acceso_no_permitido=Aliro ne permesita
acceso_admin=Via konto ne havas la necesajn permesojn por aliri ĉi tiun sekcion de la retejo.
acceso_login_texto=Vi devas ensaluti por aliri ĉi tiun sekcion de la retejo.
;LOGIN
login_texto=Vi povas uzi ĉi tiun formularon por ensaluti. Se vi ankoraŭ ne havas konton, %registrate%
login_registrate=registriĝu!
