;HEADER
cancion=Brano | Brani
lista=Playlist | Playlist
peticion=Richiesta di un brano | Richieste di brani
subir_cancion=Carica nuovi brani
base_canciones=Database dei brani
silabeador=Divisore in sillabe dei brani
reparador=Riparatore di brani
insertar=Invia nuovi brani
concursos=Concorsi
puntuacion=Punteggio | Punteggi
batallas=Sfide
programas=Programmi
ayuda=Aiuto
foro=Forum
ver_perfil=Visualizza il tuo profilo
cambiar_avatar=Cambia avatar
desconectarse=Disconnettiti
cerrar_sesion=Esci
mensajes=%mensajes% nuovo messaggio|%mensajes% nuovi messaggi
mostrar_informacion_descargas_titulo=Informazioni sui download tramite torrent
mostrar_rss_titulo=Mostra l'URL del tuo feed RSS per scaricare i brani
info_rss=Che cos'è il feed RSS e come si usa per scaricare i brani?
tiempo_conexion=Tempo di connessione
estado_servidor=Stato del server
estado_servidor_tiempo=Non attivo|Attivo %tiempo%
canciones_disponibles=Brani disponibili
descargado_total=Totale scaricato
subido_total=Totale caricato
descargado=Totale scaricato da te
subido=Totale caricato da te
ratio=Rapporto upload/download
puesto_bajada=Posizione nella classifica download
puesto_subida=Posizione nella classifica upload
conectate=Accedi
iniciar_sesion=Accedi
registrate=registrati!
registro=oppure, se non hai ancora un account, %registrate%
contraseña_olvidada=Password dimenticata?
contraseña_olvidada_titulo=Recupera la password dimenticata
reenviar_activacion=Invia nuovamente l'attivazione
reenviar_activacion_titulo=Invia nuovamente l'e-mail di attivazione
pagina_idioma=Visualizza la pagina in %idioma%
pagina_idioma_actual=Pagina visualizzata in %idioma%
;PAGINATOR
mostrando_no=Nessun %item% da visualizzare
mostrando_pagina=Visualizzazione di %total% %item%
mostrando_paginas=Visualizzazione di %item% da %desde% a %hasta% su %total%
mostrando_ultimas=Visualizzazione delle ultime %numero% %ultimas%
mostrando_ultimas_cancion=ultimi %item% aggiunti
mostrando_ultimas_lista=ultime %item% aggiornate
mostrando_ultimas_peticion=%item% dell'ultima settimana
mostrando_ultimas_puntuacion=%item% dell'ultimo giorno
mostrando_ultimas_concursos=ultimi concorsi aggiunti
ordenar_por=Ordina per
ordenadas_por=ordinate per
defecto=Predefinito
mostrar=Mostra %item%
todas=Tutte
ir_a_pagina=Vai alla pagina
ir_a_pagina_numero=Vai alla pagina %numero%
ir_a_primera=Vai alla prima pagina dei risultati
ir_a_anterior=Vai alla pagina precedente dei risultati
ir_a_siguiente=Vai alla pagina successiva dei risultati
ir_a_ultima=Vai all'ultima pagina dei risultati
ver_pagina=Visualizza la pagina %pagina% dei risultati
subir_arriba=Torna in cima
;HOME
slider_worldparty=Prova la nostra versione %worldparty%
slider_canciones=Scarica i brani dei tuoi artisti preferiti
slider_puntuaciones=Carica i tuoi punteggi e confrontali con quelli degli altri giocatori
slider_peticiones=Il tuo brano preferito non è disponibile? Puoi richiederne uno ogni mese!
algo_mas_karaoke=Molto più di un semplice karaoke sul tuo computer
algo_mas_karaoke_p1=Ti servono soltanto un microfono, un computer, il nostro %worldparty% e le migliaia di brani che mettiamo a tua disposizione.
algo_mas_karaoke_p2=Per permetterti di iniziare a cantare il prima possibile, ti mettiamo a disposizione una serie di videotutorial che spiegano il processo di installazione e configurazione del gioco.
algo_mas_karaoke_p3=Dopo averli seguiti, non ti resterà che scaricare i %canciones% che desideri, aggiungerli a %ultrastar% e dimostrare il tuo talento canoro.
algo_mas_karaoke_p4=Se hai ancora qualche dubbio, puoi consultare il resto della sezione %ayuda% oppure cercare o richiedere ulteriori informazioni nel %foro%.
ultimas_noticias=Ultime notizie
publicado_por=Pubblicato da %autor% il %fecha%
x_lecturas=%lecturas% visualizzazioni
leer_mas=Leggi tutto
ultimas_puntuaciones=Ultimi punteggi
mejores_puntuaciones_dia=Migliori punteggi del giorno
mejores_puntuaciones_semana=Migliori punteggi della settimana
mejores_puntuaciones_mes=Migliori punteggi del mese
puntuaciones_anteriores=Punteggi precedenti
puntuaciones_siguientes=Punteggi successivi
ultimas_canciones=Ultimi brani aggiunti
canciones_descargas=Brani più scaricati
canciones_descargas_mensuales=Brani più scaricati dell'ultimo mese
canciones_descargas_semanales=Brani più scaricati dell'ultima settimana
canciones_descargas_diarias=Brani più scaricati nelle ultime 24 ore
canciones_anteriores=Brani precedenti
canciones_siguientes=Brani successivi
;WORLDPARTY DOWNLOAD
worldparty_titulo2=Divertiti a cantare i tuoi brani preferiti!
worldparty_p1=Scopri il mondo di %worldparty%. Una versione migliorata che abbiamo realizzato a partire dal vecchio UltraStar Deluxe.
worldparty_p2=È senza dubbio la versione più completa e aggiornata che tu possa trovare. Include tutto ciò che ci si aspetta (punteggio durante il canto, Modalità Festa, aggiunta semplificata di nuovi brani, ecc.), insieme a un'enorme quantità di miglioramenti e nuove funzionalità.
worldparty_p3=Tra le caratteristiche più importanti troviamo: cantare in duetto con un'altra persona, eseguire versioni ridotte dei brani, la modalità Jukebox per riprodurre i brani in sequenza, inviare i propri punteggi al sito web, utilizzare la webcam del computer mentre si canta, supportare fino a 6 giocatori contemporaneamente sullo stesso schermo e molto altro ancora.
worldparty_p4=Puoi trovare tutte le informazioni nella sezione dedicata a %worldparty%.
worldparty_descargar=Scarica %worldparty%
worldparty_version_para=versione %version% per %plataforma%
;SONGS
descargar_canciones=Scarica i brani
busqueda_titulo=contenenti
ver_todas_titulo=Visualizza tutti i brani %titulo% %dato%
artista=Artista
idioma=Lingua
idioma_titulo=in
año=Anno
año_titulo=dell'anno
sin_año=Sconosciuto
subida_por=Caricato da
subida_por_titulo=caricati da
revisada_por=Invia un messaggio al revisore
valoracion=Valutazione
valoracion_titulo=Visualizza le valutazioni di %cancion%
descargas=Download
tamaño=Dimensione
fecha=Data
semillas=Seeder
sanguijuelas=Leecher
otros=Altri
baja_calidad=Brano di bassa qualità
alta_calidad=Brano di alta qualità
validada_titulo=Qualcuno ha ottenuto almeno %facil% punti in modalità Facile | %normal% punti in modalità Normale | %dificil% punti in modalità Difficile
multijugador=Multigiocatore
solo_titulo=Non è disponibile una versione per giocatore singolo
fondo_titulo=Utilizza un'immagine di sfondo invece di un video
doradas_titulo=Non contiene note dorate
creador=Creatore
artista_titulo=di
cancion_titulo=simili a
semana_titulo=caricati nella settimana del
edicion_titulo=dell'edizione
lista_titulo=della playlist
info_cancion=Visualizza tutte le informazioni di %cancion%
previsualizacion=Visualizza l'anteprima di %cancion%
copiar_video=Fai clic per selezionare l'URL del video
descargar=Scarica
descargar_titulo=Scarica il torrent di %cancion%
descargada_titulo=Scarica nuovamente il torrent di %cancion%
descargar_txt=Scarica TXT
descargar_txt_titulo=Scarica solo il file di testo di %cancion%
descargar_todas=Scarica tutti i brani visualizzati
descargar_todas_titulo=Scarica i torrent di tutti i brani visualizzati in un archivio ZIP
descargar_lista=Scarica playlist
descargar_lista_titulo=Scarica la playlist (file UPL) per raggruppare questi brani nel gioco
descargar_paquete_titulo=Scarica il pacchetto di brani (archivio ZIP) contenente i torrent di tutti i brani aggiunti
ver_paquete=Visualizza pacchetto
ver_paquete_titulo=Visualizza il contenuto del pacchetto di brani da scaricare
vaciar_paquete=Svuota pacchetto
vaciar_paquete_titulo=Svuota il pacchetto di brani in attesa di essere scaricato
eliminar_lista=Elimina playlist
eliminar_lista_titulo=Elimina playlist
canciones_lista=un brano aggiunto | %canciones% brani aggiunti
agradecer=Ringrazia
agradecer_titulo=Ringrazia il creatore che ha caricato questo brano
agradecimientos=Ringraziamenti
cerrar_informacion=Fai clic oppure premi ESC per chiudere questa finestra informativa
enlace_permanente=Collegamento permanente
enviar_por_correo=Invia tramite e-mail
compartir_en=Condividi su %red%
estadisticas=Statistiche
descargas_diarias=Download giornalieri
descargas_semanales=Download settimanali
descargas_mensuales=Download mensili
descargas_totales=Download totali
cancion_no_disponible=Brano attualmente non disponibile
no_resultados=Nessun risultato
disponibilidad=Disponibilità
descargadas_alguna_vez=Scaricati almeno una volta
descargadas_txt=Scaricati solo come TXT
descargadas_torrent_rss=Scaricati tramite torrent o RSS
actualmente_rss=Attualmente nell'RSS
quitadas_rss=Rimossi dall'RSS
no_descargadas=Mai scaricati
ultima_descarga=Dall'ultimo download
paquete=Aggiunti al pacchetto di download
mis_agradecimientos=Con i miei ringraziamenti
rss_titulo=Brani di %usuario% su %web%
rss_titulo_subir=Brani caricati da %usuario% su %web%
rss_titulo_insertar=Brani revisionati da %usuario% su %web%
;RATING
cambiar_estado=Cambia stato
abrir_categoria=Espandi/comprimi categoria
guardar_valoracion=Salva valutazione
sincronizacion=Sincronizzazione
sincronizacion_mala=Sincronizzazione accettabile
sincronizacion_aproximada=Sincronizzazione molto accurata
sincronizacion_perfecta=Sincronizzazione perfetta
duracion_mala=Durata delle note accettabile
duracion_aproximada=Durata delle note molto accurata
duracion_perfecta=Durata delle note perfetta
bpm=BPM corretto
notas=Note
tonos_minimo=Intonazione accettabile
tonos_aceptables=Intonazione molto accurata
tonos_revisados=Intonazione revisionata
notas_doradas=Contiene note dorate
notas_doradas_correctas=Note dorate posizionate correttamente
ortografia=Ortografia
errores_ortograficos=Nessun errore ortografico
tildes=Accenti, virgolette e altri simboli utilizzati correttamente
signos_puntuacion=Nessun segno di punteggiatura superfluo
capitalizacion=Le righe iniziano seguendo uno schema coerente di maiuscole e minuscole
archivos=File
tamaño_caratula=Dimensioni della copertina adeguate
audio_calidad=Qualità audio adeguata
fondo_video=Contiene un'immagine o un video di sfondo
video_sincronizado=Video sincronizzato
video_sin_sonido=Video privo di audio
tamaño_video=Dimensioni del video adeguate alla sua qualità
lineas=Righe suddivise correttamente
medley=Versione breve del brano
inicio_fin=Nessun silenzio superfluo all'inizio o alla fine
;PLAYLIST
mis_listas=Visualizza le mie playlist
mis_listas_texto=Per aggiungere brani a una delle tue playlist, aprila e poi vai nella sezione Brani seguendo le istruzioni riportate sopra. È semplicissimo!
crear_lista=Crea una nuova playlist
crear_lista_texto=Inserisci un nome e una descrizione per i brani che conterrà la playlist. Queste informazioni non potranno essere modificate successivamente, quindi cerca di renderle il più descrittive possibile.
importar_lista=Importa playlist
importar_lista_texto=Se hai delle playlist create in UltraStar, puoi importarle qui e condividerle con gli altri utenti.
importar_lista_texto2=Verranno importate solo le playlist contenenti almeno due brani e soltanto i brani il cui titolo e artista corrispondono a quelli già presenti nel database.
nombre=Nome
usuario=Utente
fecha_actualizacion=Ultimo aggiornamento
listas_propias=Create da me
buscar=Cerca
buscar_titulo=Cerca tutti i brani inclusi in questa playlist
eliminar=Elimina
creada_fecha=Creata da %usuario% il %fecha%
modificada_fecha=e aggiornata l'ultima volta il %fecha%
titulos_completos=Fai clic qui se alcuni titoli dei brani non sono visualizzati completamente
;REQUESTED
peticiones_texto=Questi sono i brani richiesti dagli utenti di %ultrastar%.
peticiones_texto2=Se il brano che desideri richiedere è già stato richiesto da qualcun altro, puoi semplicemente votarlo. In questo modo i creatori sapranno quali sono i brani più desiderati. Tieni presente, però, che questo non garantisce che vengano realizzati, né che vengano creati più rapidamente.
fecha_insercion=Data della richiesta
fecha_asignacion=Data di assegnazione
pedida_por=Richiesta da
asignada_el_dia=Assegnata il %dia%
asignada_a=Assegnata a
no_hay=Nessuno
adjuntado_por=Allegato da %usuario% il %fecha%
adjuntos=Allegati
adjuntos_titulo=Visualizza allegati
adjuntos_titulo_creadores=Disponibili per il download solo ai creatori
tipo_midi=MIDI
tipo_video=Video
tipo_caratula=Copertina
tipo_audio=Audio
tipo_txt=File di testo
nadie=Nessuno
administrar=Gestisci
peticiones_propias=Richieste da me
votaciones_propias=Votate da me
creadas_reparadas=Attualmente in lavorazione
realizadas=Completate
asignadas=Assegnate a me
existentes=Rifiutate (già esistenti)
repetidas=Rifiutate (richiesta duplicata)
datos_erroneos=Rifiutate (informazioni errate)
no_asignada=Non assegnata
asignada=In lavorazione
reparada=In riparazione
realizada=Completata
repetida=Duplicata
erronea=Errata
votos=Voto | Voti
votos_totales=Voti totali
votos_anuales=Voti annuali
votos_trimestrales=Voti trimestrali
votos_mensuales=Voti mensili
votos_semanales=Voti settimanali
votos_semana=Ti resta %votos% voto questa settimana | Ti restano %votos% voti questa settimana
votar=Vota
votar_titulo=Vota questo brano
estado=Stato
comentario=Commento
adjuntar_archivo=Allega file
editar_cancion=Modifica brano
hacer_cancion=Creerò questo brano
reparar_cancion=Riparerò questo brano
reiniciar_estado=Reimposta stato
desasignar_cancion=Rimuovi l'assegnazione di questo brano
marcar_realizada=Contrassegna il brano come completato
marcar_repetida=Contrassegna il brano come duplicato
marcar_erronea=Contrassegna il brano come errato
pedir_cancion=Richiedi un brano
pedir_cancion_titulo=Richiedi il tuo brano mensile
como_pedir_cancion=Come richiedere un brano e utilizzare questa sezione
como_pedir_cancion_titulo=Scopri come richiedere il tuo brano mensile, votare le richieste esistenti e allegare file utili ai creatori
pedir_cancion_texto=Qui puoi richiedere ogni mese un brano del tuo artista preferito. Se sarai fortunato, qualcuno potrebbe realizzarlo per te, anche se nella maggior parte dei casi potrebbe non essere mai creato oppure richiedere moltissimo tempo, persino anni.
pedir_cancion_texto2=Ti chiediamo di non pretendere nulla nei commenti. Considerati fortunato se un giorno riuscirai finalmente a cantare il brano che hai richiesto.
pedir_cancion_texto3=Prima di compilare il modulo, verifica che il brano che desideri richiedere non sia già presente tra i %canciones% oppure tra le %peticiones% esistenti.
pedir_cancion_texto4=Queste sono tutte le informazioni che puoi fornire.
adjuntar_archivo_titulo=Allega un file a %artista% - %cancion%
adjuntar_archivo_texto=Se possiedi file che possono essere utili per realizzare questo brano, allegali qui.
adjuntar_archivo_texto2=Devi fornire un collegamento al file. Se non puoi ospitarlo altrove, caricalo su %web% e utilizza quel collegamento.
adjuntar_archivo_texto3=Cerca di fornire video di buona qualità. Se il video è già disponibile su YouTube o piattaforme simili, non è necessario caricarlo nuovamente.
adjuntar_archivo_texto4=Tutti i campi sono facoltativi. Se compilati, devono contenere un URL completo, comprensivo di http:// oppure https://.
;UPLOAD
rss_subir=Questo feed RSS contiene tutti i brani che hai caricato sul sito web. Aggiungilo al tuo client per continuare a condividerli.
tutorial_subir=Tutorial sul caricamento dei brani
subir_archivos=Prima di poter generare il torrent, devi caricare i seguenti file.
boton_añadir_archivos=Aggiungi file
boton_empezar_subida=Inizia il caricamento di questo file | Inizia il caricamento di tutti i file
boton_cancelar_subida=Annulla il caricamento di questo file | Annulla il caricamento di tutti i file
boton_eliminar=Rimuovi questo file | Rimuovi i file selezionati
generar_torrent_titulo=Prima di generare il torrent, devi aver caricato tutti i file presenti nell'elenco sopra.
cancion_añadida=%cancion% è stato aggiunto correttamente alla coda di revisione. Una volta revisionato e approvato, apparirà nel database dei brani.
cancion_validada=Il brano %cancion% è stato validato correttamente.
cancion_no_validada=Il brano %cancion% non è stato validato.
cancion_doradas=Contiene %doradas% punti ottenuti con le note dorate.
cancion_doradas_porcentaje=Contiene il %doradas%% di note dorate.
cancion_jugador=del giocatore %jugador%
cancion_hash=Questo brano ha lo stesso hash di un altro brano già presente nel database.
;INSERT
autorevisor=Per poter validare i tuoi brani, devi prima caricare altre %canciones% canzoni con una valutazione superiore a %valoracion%.
limite_actualizacion=Hai aggiornato %actualizadas% brani creati da altri autori su un massimo di %limite%. Questo limite viene calcolato con un rapporto di 1:%ratio% rispetto ai brani che hai caricato: più brani realizzi, più aggiornamenti potrai effettuare.
insertar_texto=Ogni volta che assegni un brano a te stesso, esso verrà aggiunto automaticamente a questo feed RSS, che contiene tutti i brani che stai revisionando o che hai revisionato in passato.
insertar_texto_creador=Questi sono i tuoi brani in attesa di essere validati da un Super Creatore.
no_añadida_tracker=Brano non ancora aggiunto al tracker.
enviar_mensaje=Invia un messaggio privato a %usuario%
revisor=Revisore
comentario_revisor=Commento per il revisore
mostrar_comentario_revisor=Mostra/Nascondi il commento per il revisore
resubida_sin_cambios=Ricaricato senza modifiche
cancion_pedida=Brano richiesto
cancion_actualizar=Brano da aggiornare
revisar_cancion=Revisiona brano
no_revisar_cancion=Non revisionare il brano
no_editar_cancion=Non modificare il brano
valorar_cancion=Valuta brano
no_valorar_cancion=Non valutare il brano
marcar_categoria=Seleziona/Deseleziona l'intera categoria
insertar_cancion=Invia brano
eliminar_cancion=Elimina brano
canciones_nuevas_semana=%num% nuovi brani questa settimana
;HELP
realizado_por=Realizzato da %autor%
;SCORES
bajar_puntuaciones=Scarica il file dei punteggi
bajar_puntuaciones_titulo=Necessario solo per aggiornare i punteggi di %worldparty% quando non si dispone di una connessione a Internet.
subir_puntuaciones=Carica il file dei punteggi
subir_puntuaciones_titulo=Qui puoi caricare tutti i punteggi salvati localmente che non sono ancora stati inviati tramite %worldparty%.
puntos=Punti
nivel=Difficoltà
nivel_titulo=in modalità
nivel_facil=Facile
nivel_normal=Normale
nivel_dificil=Difficile
fecha_titulo=il
puntos_normales=Punti normali
puntos_lineas=Bonus di riga
puntos_doradas=Punti delle note dorate
;CONTEST
crear_duelo=Crea duello
crear_torneo=Crea torneo
crear_liga=Crea campionato
mis_concursos=I miei concorsi
clasificaciones=Classifiche
ver_concurso=Visualizza concorso
unirse_concurso=Partecipa al concorso
concursos=Concorsi
creada_por=Creato da
tipo=Tipo
rondas_cada=Turni ogni
inicio=Inizio
nivel=Difficoltà
jugadores=Giocatori
;403
acceso_no_permitido=Accesso non consentito
acceso_admin=Il tuo account non dispone delle autorizzazioni necessarie per accedere a questa sezione del sito web.
acceso_login_texto=Devi effettuare l'accesso per visualizzare questa sezione del sito web.
;LOGIN
login_texto=Puoi utilizzare questo modulo per accedere. Se non possiedi ancora un account, %registrate%
login_registrate=registrati!
