;UPLOAD
txt=Necesas alŝuti tekstdosieron
featuring_español=Por hispanlingvaj kantoj oni ne rajtas uzi "ft." aŭ "feat.". Anstataŭe uzu "y" aŭ "con".
idioma=La lingvo ne estas valida. Ĝi devas esti unu el la jenaj: %idiomas%
edicion=La eldono ne estas valida. Ĝi devas esti malplena aŭ tute ne aperi se ĝi ne apartenas al iu eldono; alikaze ĝi devas esti unu el la jenaj: %ediciones%
singstar=Vi ne rajtas alŝuti kantojn de SingStar
bpm=La BPM ne estas difinita
año=La jaro ne povas esti pli frua ol 1900 nek pli malfrua ol la nuna jaro
solo_inicio=La linio %num% enhavas nur #, kio ne estas permesita
tag_no_permitido=La etikedo %tag% ne estas permesita. Nur la jenaj etikedoj rajtas esti uzataj: %tags%
tag_multi=La etikedo %tag% estas permesita nur por plurludantaj kantoj. Por unu-ludantaj kantoj estas permesitaj nur la jenaj etikedoj: %tags%
inicio_incorrecto=La komenco de linio %num% en la tekstdosiero estas malĝusta (%letra%). Nur la jenaj signoj estas permesitaj: %letras%
numero_jugadores_incorrecto=La nombro de kantantaj ludantoj estas malĝuste indikita en linio %num% de la tekstdosiero. Ĝi devas esti indikita per P 1, P 2, P 3, ktp.
medley=Estas devige difini mallongan version de la kanto per MEDLEYSTARTBEAT kaj MEDLEYENDBEAT kiam la kantata parto daŭras pli ol 60 sekundojn.
medley_duracion=La daŭro de la mallonga versio difinita per MEDLEYSTARTBEAT kaj MEDLEYENDBEAT devas esti inter 10 kaj 60 sekundoj. Nun ĝi estas %duracion%
inicio_multi=Se la kanto estas dueto, ĝi devas komenciĝi indikante kiu ludanto kantas (P 1, P 2, ktp.), sed ĉi tie neniu estas indikita.
error_jugador=de ludanto %jugador%
error_linea=Linio %linea%%jugador%.%salto%%error%
notas_solapadas=Interkovriĝantaj notoj
salto_linea=Linisalto malĝuste lokita
notas_juntas=Notoj tro proksimaj unu al la alia
nota_pegada_salto=La lasta noto estas algluita al la linisalto
doradas_puntuacion=La kanto %jugador%havas %doradas% poentojn en oraj notoj. Ĝi devus havi inter 1000 kaj 1500
doradas_porcentaje=La kanto %jugador%havas %porcenaje%% da oraj notoj. Ĝi devus havi inter 10% kaj 15%
duetsinger=La nomoj de la kantistoj devas esti difinitaj per DUETSINGERP1 kaj DUETSINGERP2
caratula=La kovrilbildo indikita en #COVER havas malĝustan nomon. Ĝi devus esti %nombre%
mp3_video=La #%tag% havas malĝustan nomon. Ĝi devus esti %nombre%
background=La #BACKGROUND havas malĝustan nomon. Ĝi devus esti %nombre%
minimo_cancion=La kanto devas enhavi almenaŭ titolon, artiston, lingvon, jaron, kovrilbildon kaj la kantotekston
tag_multi_coicidencia=La etikedo %tag% en la unu-ludanta tekstdosiero estas %nombre%, sed ĝi ne kongruas kun tiu de la dueto, kiu estas %nombre_multi%
torrent_tamaño=La grandeco de la torrent-dosiero estas tro granda. Ĝi devas esti malpli ol 1 MB
torrent_extension=La etendaĵo %ext% de la torrent-dosiero ne estas valida. Ĝi devas esti .torrent
torrent_mimetype=La dosiero ne estas valida torrent-dosiero
torrent_mas_archivos=La torrent-dosiero enhavas pli da dosieroj ol estas permesite
torrent_piezas=La grandeco de la pecoj en la torrent-dosiero superas 256 KB, kio ne estas permesita
torrent_carpeta=La dosierujo enhavanta la kanton en la torrent-dosiero havas malĝustan nomon. Ĝi devus esti %nombre_cancion% anstataŭ %nombre_torrent%.%importante%: Se la ĉi tie proponita nomo ne estas ĝusta ĉar mankas litero en iu vorto, ne renomigu ion. Anstataŭe kodigu la tekstdosieron per UTF-8 antaŭ ol alŝuti ĝin.
importante=GRAVE;
torrent_nombre=La torrent-dosiero %archivo% ne havas la ĝustan nomon. Ĝi devus esti %nombre%
torrent_txt=La nomo de la tekstdosiero ne estas ĝusta. Ĝi devus esti %nombre% anstataŭ %archivo%
torrent_txt_multi=La nomo de la plurludanta tekstdosiero ne estas ĝusta. Ĝi devus esti %nombre% anstataŭ %archivo%
torrent_txt_coincidencia=La alŝutita tekstdosiero ne kongruas kun tiu en la torrent-dosiero
torrent_formato_caratula=La kovrilbildo devas esti en formato PNG aŭ JPEG
torrent_caratula_tamaño_coincidencia=La alŝutita kovrilbildo ne kongruas kun tiu en la torrent-dosiero
torrent_caratula_coincidencia=La nomo de la kovrilbildo en la torrent-dosiero %archivo% ne kongruas kun tiu indikita en la tekstdosiero %nombre%
torrent_video_coincidencia=La nomo de la videodosiero en la torrent-dosiero %archivo% ne kongruas kun tiu indikita en la tekstdosiero %nombre%
torrent_dentro=La torrent-dosiero ne rajtas enhavi alian torrent-dosieron
torrent_archivo_no_permitido=La dosiero %archivo% en la torrent-dosiero ne estas permesita
torrent_archivo_no_txt=La dosiero %archivo% ne aperas en la tekstdosiero de la kanto
torrent_announce=La announce-URL devas esti %announce% anstataŭ %announce_torrent%
torrent_privado=La privata flago ne estas aktivigita en la torrent-dosiero
torrent_igual=La dosiero jam estis alŝutita en la datumbazon. Se vi modifis la kanton, vi devas krei novan torrent-dosieron
subir_imagen=Malsukcesis alŝuti la bildon
guardar_txt=Malsukcesis konservi la tekstdosieron
guardar_txt_multi=Malsukcesis konservi la tekstdosieron MULTI
guardar_torrent=Malsukcesis konservi la torrent-dosieron
guardar_bd=Malsukcesis aldoni la kanton al la datumbazo
