;COMMON
todos=Ĉiuj
todas=Ĉiuj
requerido=Deviga kampo
;SEARCH
busqueda=Kion vi volas kanti hodiaŭ?
tipo=Serĉi laŭ
tipo_empty=Artisto, kanto aŭ komento
buscar=Serĉi
reiniciar=Restarigi formularon
artista=Artisto
cancion=Kanto
lista=Kantolisto
idioma=Lingvo
creador=Kreinto
;LISTS
nombre_lista=Nomo de la ludlisto
archivo_lista=UPL-dosiero enhavanta la ludliston
descripcion_lista=Priskribo de la enhavo
categoria_lista=Kategorio de la ludlisto
crear_lista=Krei ludliston
importar_lista=Importi ludliston
;REQUESTED
peticion=Serĉi petitajn kantojn
titulo_cancion=Titolo de la kanto
año_lanzamiento=Eldonjaro de la kanto
selecciona_año=(Elektu jaron)
comentario_peticion=Komento pri la kanto aŭ alia informo
nueva_peticion=Peti kanton
actualizar_peticion=Ĝisdatigi peton
midi=MIDI- aŭ KAR-dosiero
comentario_midi=Komento pri la MIDI- aŭ KAR-dosiero
caratula_peticion=Kovrilbildo de la unuopaĵo aŭ de la unua albumo en kiu aperis la kanto
comentario_caratula_peticion=Komento pri la kovrilbildo
audio=Aŭdio (mp3, ogg, wma, ktp.)
comentario_audio=Komento pri la aŭdiodosiero
video=Video (mp4, mpg, avi, ogm, wmv, mkv, ktp.)
comentario_video=Komento pri la videodosiero
texto_peticion=Tekstdosiero de la kanto
comentario_texto_peticion=Komento pri la tekstdosiero
adjuntar=Aldoni
;UPLOAD
prevalidacion=Antaŭvalidigi la kanton
texto=Tekstdosiero de la kanto
multi=Plurludanta tekstdosiero de la kanto
caratula=Kovrilbildo de la kanto
torrent=.torrent-dosiero de la kanto
previsualizacion=Antaŭrigardo de la kanto (YouTube-videoidentigilo)
comentario=Komento pri la kanto
comentario_revisor=Komento por la revizianto (videbla nur al li, ne publika)
cancion_actualizar=Ĝisdatigota kanto
cancion_actualizar_defecto=Neniu, temas pri kanto ankoraŭ ne aldonita al la datumbazo
cancion_peticion=Petita kanto atribuita al mi
cancion_peticion_defecto=Neniu, temas pri kanto ne atribuita al mi
cancion_peticion_editar=Petita kanto atribuita al kreinto
cancion_peticion_editar_defecto=Neniu, temas pri kanto ne atribuita al iu ajn kreinto
no_validada=Aldoni kiel NE validigitan
subir=Alŝuti
generar_torrent=Generi torrenton
editar=Redakti
;SYLLABICATOR
letra=Teksto de la kanto por silabigi
separador=Programo en kiu la kanto estos uzata
silabear=Silabigi
;REPAIR
doradas=Provi korekti la orajn notojn (ne ĉiam eblas)
reparar=Ripari
;BASE
longitud_nota=Daŭro de la notoj
bpm=BPM de la kanto
transformar=Transformi
;SCORES
busqueda_concursos=Serĉi artiston aŭ kanton
tipo_concursos_empty=Artisto aŭ kanto
usuario=Uzanto
nivel=Nivelo
facil=Facila
normal=Normala
dificil=Malfacila
fecha=Dato
archivo_puntuaciones=Poentodosiero
subir_puntuaciones=Alŝuti poentarojn
;CONTEST
tipo_concurso=Speco de konkurso
maximo_jugadores=Maksimuma nombro da ludantoj
ilimitado=Senlima
rango_dia=1 tago | %dias% tagoj
rango_minutos=%minutos% minutoj
descripcion_concurso=Priskribo de la konkurso
concurso_privado=Privata konkurso. Ĝi estos videbla por ĉiuj, sed nur ludantoj invititaj de la kreinto povos partopreni
selecciona=(Elektu opcion)
