;COMMON
todos=Tutti
todas=Tutte
requerido=Campo obbligatorio
;SEARCH
busqueda=Che cosa vuoi cantare oggi?
tipo=Cerca per
tipo_empty=Artista, brano o commento
buscar=Cerca
reiniciar=Reimposta modulo
artista=Artista
cancion=Brano
lista=Elenco dei brani
idioma=Lingua
creador=Autore
;LISTS
nombre_lista=Nome della playlist
archivo_lista=File UPL contenente la playlist
descripcion_lista=Descrizione del contenuto
categoria_lista=Categoria della playlist
crear_lista=Crea playlist
importar_lista=Importa playlist
;REQUESTED
peticion=Cerca brani richiesti
titulo_cancion=Titolo del brano
año_lanzamiento=Anno di pubblicazione del brano
selecciona_año=(Seleziona l'anno)
comentario_peticion=Commento sul brano o qualsiasi altra informazione
nueva_peticion=Richiedi un brano
actualizar_peticion=Aggiorna richiesta
midi=File MIDI o KAR
comentario_midi=Commento sul file MIDI o KAR
caratula_peticion=Copertina del singolo o del primo album in cui è stato pubblicato il brano
comentario_caratula_peticion=Commento sulla copertina
audio=Audio (mp3, ogg, wma, ecc.)
comentario_audio=Commento sul file audio
video=Video (mp4, mpg, avi, ogm, wmv, mkv, ecc.)
comentario_video=Commento sul file video
texto_peticion=File di testo del brano
comentario_texto_peticion=Commento sul file di testo
adjuntar=Allega
;UPLOAD
prevalidacion=Prevalida il brano
texto=File di testo del brano
multi=File di testo del brano multigiocatore
caratula=Copertina del brano
torrent=File .torrent del brano
previsualizacion=Anteprima del brano (ID del video di YouTube)
comentario=Commento sul brano
comentario_revisor=Commento per il revisore (sarà visibile solo a lui e non sarà pubblico)
cancion_actualizar=Brano da aggiornare
cancion_actualizar_defecto=Nessuno, è un brano non ancora presente nel database
cancion_peticion=Brano richiesto assegnato a me
cancion_peticion_defecto=Nessuno, è un brano che non mi è stato assegnato
cancion_peticion_editar=Brano richiesto assegnato a un autore
cancion_peticion_editar_defecto=Nessuno, è un brano non assegnato ad alcun autore
no_validada=Aggiungi come NON validato
subir=Carica
generar_torrent=Genera torrent
editar=Modifica
;SYLLABICATOR
letra=Testo del brano da dividere in sillabe
separador=Programma in cui verrà utilizzato il brano
silabear=Dividi in sillabe
;REPAIR
doradas=Prova a correggere le note dorate (non sempre è possibile)
reparar=Ripara
;BASE
longitud_nota=Durata delle note
bpm=BPM del brano
transformar=Trasforma
;SCORES
busqueda_concursos=Cerca artista o brano
tipo_concursos_empty=Artista o brano
usuario=Utente
nivel=Livello
facil=Facile
normal=Normale
dificil=Difficile
fecha=Data
archivo_puntuaciones=File dei punteggi
subir_puntuaciones=Carica punteggi
;CONTEST
tipo_concurso=Tipo di concorso
maximo_jugadores=Numero massimo di giocatori
ilimitado=Illimitato
rango_dia=1 giorno | %dias% giorni
rango_minutos=%minutos% minuti
descripcion_concurso=Descrizione del concorso
concurso_privado=Concorso privato. Sarà visibile a tutti, ma potranno partecipare solo i giocatori invitati dal creatore del concorso
selecciona=(Seleziona un'opzione)
